# Generated by Django 3.2.6 on 2021-08-05 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128, verbose_name='Тема рассылки')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Тело рассылки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('sending_date', models.DateTimeField(verbose_name='Время рассылки')),
                ('finished', models.BooleanField(default=False)),
                ('recipients', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
        ),
    ]
