# Generated by Django 3.2.6 on 2021-08-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='sending_date',
        ),
    ]
